### ISSUE TITLE
only autocomplete tags if the tag is opened

### ISSUE THREAD

**Issue by StevenClontz** [oscarlevin/pretext-tools#3]
When I'm trying to write the word `answer` in a text node, the plugin wants to turn it into an `<answer>` tag. I'm only wanting completion if I've started writing a tag, e.g. writing `an` should do nothing, but `<an` should suggest `<answer>` and `<assumption>`.

**Comment by StevenClontz** [comment]
This might be a misunderstanding on my part on how VS Code is used to author XML-like documents. I noticed there's a built-in extension called Emmet that does similar completion even when I don't want it. I disabled it, but I should probably learn more about efficient authoring of XML in VS Code in general...

**Comment by oscarlevin** [comment]
I think this is a valid point worthy of discussion.  It would be easy to make the recipe for snippets require `<` at the start, but I found that this was a hassle to type (especially for shorter tags like `<m>` or `<p>`).  Maybe I just need to get used to it though.  As you say, Emmet does snippets without the `<`.  

I disable Emmet and also the general autocomplete.  Perhaps there are other settings (that I should document) that would make this easier to use, instead of changing the snippet recipes.  For example, you can change which of TAB and ENTER select snippets.

**Comment by StevenClontz** [comment]
I guess the real pain point was when I was trying to write something like this sentence

```
<p>The interval <m>(1,3)</m> is an
open subset of the real line.</p>
```

Because I enter after `an`, it created an answer tag. But I cannot think of a good reason to put tabs within of a text node, so maybe swapping ENTER to TAB is a good fix?

**Comment by StevenClontz** [comment]
On the other hand, I think deciding to start a tag should be a purposeful decision, so requiring `<` still seems like a reasonable way to express that.

If we need a quick shortcut for `<m/>`, how about `$`? :-)

**Comment by oscarlevin** [comment]
Thinking about this more, it looks like it is easy to allow *both* `<` and not for a particular snippet (using the `"prefix": ["p", "<p>"],` construction.  That might be a reasonable first step.  This doesn't address snippets being triggered accidentally the way requiring (most of) them to start with `<` would.  

What I ended up doing to avoid the accidental triggering is to remove "enter" as a key that triggers the autocomplete.  This is a setting available in VS code, but perhaps not a good universal fix.

**Comment by stevenbell** [comment]
I'd also prefer an option to not autosuggest any snippets until I've started typing a tag (with an opening `<` character).  In addition to not accidentally filling in snippets where I just wanted a word, this would also cut down on the amount of visual noise as I type by not bringing up the completion box when I'm just writing text.

**Comment by StevenClontz** [comment]
> If we need a quick shortcut for `<m/>`, how about `$`? :-)

I was kidding a year ago, but reading it with wisdom that only comes with age (I suppose lol) I non-ironically think this is a good idea.

**Comment by oscarlevin** [comment]
I think this would be really nice, but I don't know how to implement it.  VSCode's autocomplete system seems to pick up fuzzy suggestions for snippets (and everything else).  I am not aware of a way for a package to modify this behavior for just it's snippets.    Over break I'll try to look into it more though.

**Comment by angelozerr** [comment]
IMHO, I think you should not manage pretext with snippet because snippet have not the capability to appears according a given context. For instance you display `<answer>` snippet anywhere although `answer` is avaialble only inside `example` element according to the pretext relaxng schema.

If you use vscode-xml, the `answer` element tag name will appear only if you are typping  `answer` inside an `example` element. So you will not have the problem described in this issue.

Here a screenhot,where answer tag element is allowed

![image](https://user-images.githubusercontent.com/1932211/210138328-8e864459-fc48-4247-a26f-0e1910310d1e.png)

Here a screenhot,where answer tag element is not allowed:

![image](https://user-images.githubusercontent.com/1932211/210138360-6fb67c2e-ddee-4981-aed5-132acff20d73.png)

As you can notice, vscode-xml doesn't show the `answer ` tag element.

**Comment by oscarlevin** [comment]
I would love to have context aware auto-complete instead of the current snippet "features".  There are quite a few snippets that do snippet-like things: putting more formatting/tags in, tab-stops, etc.  I don't understand enough about writing extensions to know whether this is possible with autocomplete, especially if piggybacking on another application.  If you @angelozerr have a suggestion of where I could look to learn more, I'd appreciate it.

**Comment by angelozerr** [comment]
You cannot manage  completion aware with vscode snippet.

vscode xml manages this usecase in lsp server side. It maintains a DOM document in memory and the relaxng schema. When completion is triggered, it takes the parent element of the triggered completion offset and uses the schema to know the allowed element.

What about delegating this work to vscode-xml by removing your snippet?

Perhaps you would like to keep your snippet because yiu find that there are better than vscode xml completion. If it that please create an issue 8n vscode xml. An idea that ,i have is to register snippets in package.json with xmlParticipants like you are using to register ptx languae client.
Those snippet will be managed by xml lsp server in completion which will return the snippets instead of simple and generic completion item.

**Comment by angelozerr** [comment]
@oscarlevin IMHO you should remove your snippets, but I think you could be interested with https://github.com/eclipse/lemminx/issues/1468

It will give the capability to register on lemminx side your snippet and override the current behavior of lemminx completion.

**Comment by oscarlevin** [comment]
Closed with https://github.com/oscarlevin/pretext-tools/pull/67
