### ISSUE TITLE
Support for autocompletion of xref xml:ids

### ISSUE THREAD

**Issue by StevenClontz** [oscarlevin/pretext-tools#30]

**Comment by angelozerr** [comment]
vscode xml provide the xml.references to manage this usecase , see https://github.com/redhat-developer/vscode-xml/blob/main/docs/Features/XMLReferencesFeatures.md#attribute-node-references-fooattr

Once you will have declared in settings the proper références you will benefit with completion validation hyperlink find références and rename.

There are some few limitation when you will use included document. Please read the doc

**Comment by angelozerr** [comment]
@oscarlevin as you have defined a default vscode-xml settings for pretext, I think this issue can be closed, no?

**Comment by StevenClontz** [comment]
It does suggest xml:ids from the currently edited file, but does not see any xml:ids from other files in the PreTeXt project.

**Comment by angelozerr** [comment]
> It does suggest xml:ids from the currently edited file, but does not see any xml:ids from other files in the PreTeXt project.

Scanning all files from the project could degrade the performance, but if you use xi:include it should work no?

**Comment by oscarlevin** [comment]
It's somewhere in between now.  Any xi:included file works (i.e., you see suggestions of refs in files that are below your current file in the tree).  But you don't look up the tree.

I agree that scanning all files seems like the wrong thing to do (and would be incorrect if you had files that are not part of the main document anyway).  What about finding the root document, or setting it as a default for the workspace, and always scanning the xml tree from there?  I haven't looked at any code yet, but perhaps there is a way to leverage the xml extension for this purpose.  So instead of using the current file, use `main.ptx` in whatever search it uses.

@angelozerr, do you think a setting like this would be useful for other users of the xml extension?  Perhaps an upstream contribution would be worthwhile?

**Comment by angelozerr** [comment]
For the moment there are no way to customize the files scope to scan. Please create an issue in lemminx side with your suggestion in détail.

**Comment by oscarlevin** [comment]
Done here: https://github.com/eclipse/lemminx/issues/1576

**Comment by oscarlevin** [comment]
I have implemented a version of this directly in pretext-tools now.  At startup, the extension scans all the files for xml:ids and stores them.  Whenever a file is saved, it refreshes the ids for that file.  Seems to be working well so far.  Could give false positives if you have files that are not included but still in your source directory.
